const data = [
    {
      title: "Yashamoq",
      author: "Yuy Xua",
      genre: "Roman",
      published: "2024",
      description: "Kitobda Xitoy madaniy inqilobidan avval katta meros va boylikka ega boʻlgan Fugui va uning oilasi misolida bir mamlakatning aholisi va ijtimoiy mavqei oʻzgarishi tasvirlangan. Boshdan kechirilgan ocharchiliklar, katta temir eritish kampaniyasi, yerning davlat mulkiga aylantirilishi, xususiy mulkchilikning bekor qilinishi, taomlarning oshxonalarda isteʼmol qilinishi kabi tub oʻzgarishlarga kichik qishloqda qanday munosabat bildirilgani haqida hikoya qilinadi.",
      image: "https://i.pinimg.com/736x/3b/74/50/3b7450909ca393f09fcf896f2a1164f8.jpg",
      pdf: "https://t.me/SakinatPdfAudioKitoblar/12",
      audio: "/audio/muhabbat-asirligi.mp3",
    },
    {
      title: "Men Robiya",
      author: "Sa'diya Erol Aykach",
      genre: "Tarixiy Roman, Biografiya",
      published: "2023",
      description: " Ushbu kitob: oʻsha yoʻllarni bizdan avval bosib oʻtgan, haqni idrok qila olgan Robiyatul Adaviya haqlarida...",
      image: "https://i.pinimg.com/736x/a5/91/94/a5919434935f7ffc45cc38e6723ae61c.jpg",
      pdf: "https://t.me/SakinatPdfAudioKitoblar/14",
      audio: "https://t.me/SakinatPdfAudioKitoblar/13",
    },
    {
      title: "Dard etma, Alloh yetar",
      author: "Kadir Akel",
      genre: "Roman",
      published: "2024",
      description: "Ehtimol, xastadirsan. Ehtimol, yolg'izdirsan. Ehtimol, eng og'ir dardlar changalidadirsan. Ammo unutma: hamisha ikki tanloving bor: yo mana shu muammolar iskanjasida qiynalib, isyonga ketib, o'zing uchun ham, atrofingdagilar uchun ham bu hayotni zahar qilasan, yoki (Ey Robbim! Sendan kelgan har narsaga boshu ko'zimning ustiga) deya, shukur aylab, bu hayotdan bahra olasan. Ishon, bir kun g'amlar ketar, Dard etma Alloh yetar!",
      image: "https://i.pinimg.com/736x/ba/f5/b7/baf5b73769cc9b7560293406b11cb6f5.jpg",
      pdf: "",
      audio: "https://t.me/SakinatPdfAudioKitoblar/15",
    },
    {
      title:"MEN (Bas qil ey nafs)",
      author: "Fotih Duman",
      genre: "Aziz Maxmud Xudoiy romani",
      published: "2022",
      description: "Bizlarni ishdan qoldirgan, aldab-suldagan ham nafsdir.Hatto ichingizdan bir ovoz sizga (bu kitobni aslo va aslo o'qima) deyotgan bo'lsa bilingki bu ham nafsdir. Har bir kitobning o'z egasi bor deydilar va ajab emas bu kitob faqatgina siz uchun yozilgan bo'lsa",
      image: "https://i.pinimg.com/736x/60/32/34/603234d51ca36a5a5bb6c956612ae3a0.jpg",
      pdf: "https://t.me/SakinatPdfAudioKitoblar/16",
      audio: "https://t.me/SakinatPdfAudioKitoblar/17",
    },
    {
      title:"Qo'zichoqlar sukunati",
      author: "Tomas Harris",
      genre: "Detektiv",
      published: "2023",
      description: "Amerikalik yozuvchi Tomas Harrisning (Qo'zichoqlar sukunati) o'tkir syujetli detektiv asari xalqaro bestseller hisoblanadi. Zamonaviy psixologik triller janriga oid mazkur kitob o'n sakkiz yoshdan oshgan kitobxonlarga mo'ljallangan. Voqealar rivoji o'quvchiga yovuz jinoyatchilarning ichki olami, qarashlari, o'ziga xos jihatlarini tanitadi. Seriyali qotilliklar sodir etgan noma'lum shaxs ortidan tushgan jasur va qat'iyatli kursant qiz Kleris Starling qo'lga kiritgan dalillar yechimi va mantiqiy xulosalari, umuman olganda igna bilan quduq qazishdek murakkab izlanishlari oxir-oqibatda, o'z samarasini beradimi? Kasbi tikuvchi bo'lgan qotil erkak nega faqat aynan ayollarni qurbon sifatida tanladi? Kursant qizning tushlariga bot-bot kirib bezovta qiluvchi, bolalikdagi ruhiy olami og'riqlaridan meros - tun zulmatidagi qo'zichoqlarning zorlanib ma' rashi barham toparmikan? Asarning shiddatli, qo'rqinchli, kutilmagan burilishlarga boy zavqli mutolaasi orqali ana shu savollarga javob topishingiz mumkin.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6FZzoLRpUVRD69eH22IMi3BPnieNrM3qgPg&s",
      pdf: "",
      audio: "",
    },
    {
      title:"Qizlar oramizda qolsin",
      author: "Hafsa Bilgin",
      genre: "Pand-nasihat",
      published: "2024",
      description: "Hafsa Bilgin tomonidan yozilgan va Nigora Usmonova tomonidan tarjima qilingan bu kitob, hayotda uchraydigan qiyinchiliklarni yengib oʻtish, vaqtni samarali rejalashtirish va oʻz-oʻzini anglash yoʻlida qimmatli maslahatlar beradi. 136 betlik bu asar, oʻquvchilarga oddiy va tushunarli tilda hayotiy zarur bilimlarni taqdim etadi. Kitobda insonning ichki olami, hayotiy qadriyatlar va kundalik odatlar haqida muhim maʼlumotlar jamlangan. Agar siz oʻz maqsadlaringiz sari intilish, vaqtni boshqarish va hayotingizga tartib kiritish istagida boʻlsangiz, bu kitob siz uchun moʻljallangan.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPj7Bid-4baVJK1-T9lMDVbXC0zGpfMBsRJuIBGj8t157LUwqvBnNm6T2WqgIz0vRAlOg&usqp=CAU",
      pdf: "",
      audio: "",
    },
  ];
  
  export default data;
  